service: train-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1

functions:
  stations:
    handler: handler.stations
    events:
      - http:
          path: v1/stations
          method: get
          cors: true
  current:
    handler: handler.current
    events:
      - http:
          path: v1/current
          method: get
          cors: true
  stationData:
    handler: handler.stationData
    events:
      - http:
          path: v1/stationData
          method: get
          cors: true
  stationSearch:
    handler: handler.stationSearch
    events:
      - http:
          path: v1/stationSearch
          method: get
          cors: true
  trainMovements:
    handler: handler.trainMovements
    events:
      - http:
          path: v1/trainMovements
          method: get
          cors: true
  haconTrains:
    handler: handler.haconTrains
    events:
      - http:
          path: v1/haconTrains
          method: get
          cors: true